resolver: lts-11.13

# packages:
#  - location:
#     git: git@github.com:forsyde/forsyde-atom.git
#     commit: 59aeeb6130bc3fa4665aebd2634ebe3a575a7208
#    extra-dep: true

packages:
- .

extra-deps:
- normaldistribution-1.1.0.3
- git: git@github.com:forsyde/forsyde-atom.git
  commit: 6b9cc94775fdcc556126cc0f3aa1fd54d05b4491


# Override default flag values for local packages and extra-deps
# flags: {}
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
