name:                sdf-tutorial
version:             0.1.0.0
github:              "forsyde/forsyde-atom-examples/sdf-tutorial"
license:             BSD-3-Clause
author:              "Ingo Sander"
maintainer:          "ingo@kth.se"
copyright:           "Ingo Sander"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/forsyde/forsyde-atom-examples/sdf-tutorial#readme>

dependencies:
- base >= 4.7 && < 5
- forsyde-atom >=0.3.2 && <0.3.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  sdf-tutorial-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdf-tutorial

tests:
  sdf-tutorial-example-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sdf-tutorial
